export BASH_SILENCE_DEPRECATION_WARNING=1
export TERM='screen-256color'
export LANG='C.UTF-8'
export HISTSIZE=1024
export HISTTIMEFORMAT='%F %T '
export HISTIGNORE="c:l:ls:ll:lc:cl:p:history:cd:u:m:mc:mcm"
export GPG_TTY=$(tty)

alias a='alias'
alias c='clear'
alias ccd='cd'
alias h='hostname'
alias rm='rm -i'
alias t='top'
alias x='cat'
alias m='make'
alias mc='make clean'
alias mcm='make clean; make'
alias mi='make -j install'
alias mj='make -j'
alias mv1='make VERBOSE=1'
alias g='git'
alias gl='git log --oneline --decorate --all --graph'
alias gs='git status'
alias gd='git diff'
alias gt='git difftool'
alias gc='git commit -a -m'
alias sc='screen -U'
alias v='vim'
alias vi='vim'
alias iv='vim'
alias ls='ls --color=auto'
alias l='ls -l'
alias ll='ls -al'
alias lns='ln -nfs'
alias cl='clear; ls -l'
alias lc='clear; ls -l'
alias cls='clear; ls'
alias grep='grep --colour=auto'
alias tf='tail -f'
alias u='cd ..'
alias p='cd ..; clear; ls -l'

test -s bashrc.machine && . bashrc.machine || true
